exclude:
  paths:
    - ^pkg/subroutines/mocks # exclude generated mock files
    - api/v1alpha1 # skipping generated files and crd type definitions
    - main\.go$ # skip covering main.go
    - ^cmd # skip covering cmd directory
    - ^pkg/testing/kcpenvtest # skip covering kcpenvtest
    - ^internal/controller # skip controller integration tests (requires KCP setup)
    - pkg/subroutines/workspacetype\.go # TODO: improve test coverage for WorkspaceType (requires complex KCP mocking?)
