apiVersion: v1
kind: Service
metadata:
  name: account-operator-webhook-service
  namespace: platform-mesh-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
